### ISSUE TITLE
Rename this repo astropy-learn?

### ISSUE THREAD

**Issue by adrn** [astropy/learn-astropy#18]
Same discussion for all other astropy organization repos: when forked, this becomes, e.g., adrn/learn, which is a bit ambiguous.

**Comment by jonathansick** [comment]
@adrn I'd be happy with the change. This has no impact on GitHub Pages URLs, correct?

**Comment by jonathansick** [comment]
Done! Let's try it as "learn-astropy" for branding sake. If we want to standardize back to "astropy-learn" for consistency with other code repos we can do that instead in the future.
